[package]
name = "neothesia-iced-widgets"
version = "0.1.0"
edition = "2021"

[dependencies]
iced_graphics.workspace = true
iced_core.workspace = true
iced_wgpu.workspace = true
iced_widget.workspace = true

piano-math = { workspace = true }
