[package]
name = "midi-io"
version = "0.1.0"
edition = "2021"

[dependencies]
midir = "0.10"
serde_json = "1.0.117"
reqwest = { version = "0.12.4", features = ["json"] }
tokio = { version = "1.38.0", features = ["full"] }
warp = "0.3.7"
serde = "1.0.203"
